# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver = "2"
members = ["day*"]

[workspace.dependencies]
itertools = "0.12.0"
rayon = "1.8.0"
regex = "1.10.2"


